{
 "title": "linux operating system",
 "tags": [ "node-exporter" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "group name",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "node",
    "label": "server name",
    "query": "label_values(node_uname_info{job=~\"$job\"},instance)"
   },
   {
    "name": "mountpoint",
    "query": "label_values(node_filesystem_avail_bytes{instance=\"$node\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}, mountpoint)"
   },
   {
    "name": "device",
    "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   }
  ]
 },
 "panels": [
  {
   "title": "server time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=~\"$job\",instance=~\"$node\"} * 1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - (max by (instance) (node_boot_time_seconds{instance=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "cpu count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=~\"$job\",instance=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "memory size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$node\"} "
    }
   ]
  },
  {
   "title": "swap size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=~\"$job\",instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "/ size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=~\"$job\",instance=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "No of Disk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_disk_io_time_seconds_total{job=~\"$job\", instance=~\"$node\",device!~\"dm-[0-9]\"})"
    }
   ]
  },
  {
   "title": "No of interface",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_network_info{job=~\"$job\", instance=~\"$node\",device=~\"$device\"})"
    }
   ]
  },
  {
   "title": "uptime graph",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "up{job=~\"$job\",instance=~\"$node\"} == 1",
     "legendFormat": "uptime graph"
    }
   ]
  },
  {
   "title": " remote users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_logind_sessions{job=~\"$job\", type=\"tty\", class=\"user\",seat!=\"seat0\", remote=\"true\", instance=~\"$node\"} > 0",
     "legendFormat": "$node - remote users login"
    }
   ]
  },
  {
   "title": "login session",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_logind_sessions{job=~\"$job\", type=\"tty\", class=\"user\",seat!=\"seat0\", remote=\"true\", instance=~\"$node\"}",
     "legendFormat": "remote login"
    },
    {
     "expr": "node_logind_sessions{job=~\"$job\", type=\"x11\", class=\"user\",seat!=\"seat0\", remote=\"true\", instance=~\"$node\"}",
     "legendFormat": "console login"
    }
   ]
  },
  {
   "title": "console login",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_logind_sessions{job=~\"$job\", type=\"x11\", class=\"user\",seat!=\"seat0\", remote=\"true\", instance=~\"$node\"}",
     "legendFormat": "$node - console login"
    }
   ]
  },
  {
   "title": "Listen",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"listen\"}"
    }
   ]
  },
  {
   "title": "Sync Sent",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"sync_sent\"}"
    }
   ]
  },
  {
   "title": "Sync Recevied",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"sync_recv\"}"
    }
   ]
  },
  {
   "title": "Establish ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_tcp_connection_states{state=\"established\",job=~\"$job\",instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Fin Wait1 ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"fin_wait1\"}"
    }
   ]
  },
  {
   "title": "Fin Wait2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"fin_wait2\"}"
    }
   ]
  },
  {
   "title": "close wait",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"close_wait\"}"
    }
   ]
  },
  {
   "title": "load 1m  %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 1, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_load1{job=~\"$job\",instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "load 5m  %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_load5{job=~\"$job\",instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "load 15m  %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_load15{job=~\"$job\",instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "cpu usage %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=~\"$job\",instance=~\"$node\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"$job\",instance=~\"$node\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=~\"$job\",instance=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "time wait",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"closed\"}"
    }
   ]
  },
  {
   "title": "time wait",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"closed\"}"
    }
   ]
  },
  {
   "title": "closing",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"closing\"}"
    }
   ]
  },
  {
   "title": "root usage %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "memory usage %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"})  / (node_memory_MemTotal_bytes{instance=~\"$node\"})) * 100 "
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{instance=~\"$node\",fstype=~\"(ext.|xfs|vfat)\"}) without (mountpoint)) without (device,fstype)"
    }
   ]
  },
  {
   "title": "Disk free %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(node_filesystem_free_bytes{instance=~\"$node\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"}/node_filesystem_size_bytes{instance=~\"$node\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"})*100"
    }
   ]
  },
  {
   "title": "swap usage %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$node\"} - node_memory_SwapFree_bytes{instance=~\"$node\"})  / (node_memory_SwapFree_bytes{instance=~\"$node\"})) * 100 "
    }
   ]
  },
  {
   "title": "inbound",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(irate(node_network_receive_bytes_total{job=~\"$job\"}[5m])*8) by (instance)"
    }
   ]
  },
  {
   "title": "outbound",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(irate(node_network_transmit_bytes_total{job=~\"$job\"}[5m])*8) by (instance)"
    }
   ]
  },
  {
   "title": "tcp connection states",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"listen\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"sync_sent\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"sync_recv\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"established\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"fin_wait1\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"fin_wait2\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"close_wait\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"closing\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"last_ack\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"time_wait\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", instance=~\"$node\", state=\"closed\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Load avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=~\"$job\", instance=~\"$node\"}",
     "legendFormat": "1min"
    },
    {
     "expr": "node_load5{job=~\"$job\", instance=~\"$node\"}",
     "legendFormat": "5min"
    },
    {
     "expr": "node_load15{job=~\"$job\", instance=~\"$node\"}",
     "legendFormat": "15min"
    }
   ]
  },
  {
   "title": "process fork state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_forks_total{instance=~\"$node\"}[1m]) * 10",
     "legendFormat": "forks"
    }
   ]
  },
  {
   "title": "CPU Core Utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "clamp_max(avg by () ((sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{instance=\"$node\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1))*100 )) or max_over_time(node_cpu_average{instance=~\"$node\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m])) ,100)",
     "legendFormat": "Avg"
    },
    {
     "expr": "clamp_max((sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{instance=\"$node\",mode!=\"idle\",mode!=\"iowait\"}[5m])*100,100)) )) or sum by (cpu) (max_over_time(node_cpu_average{instance=~\"$node\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m])) ,100)",
     "legendFormat": "cpu {{cpu}}"
    }
   ]
  },
  {
   "title": "memory utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"} - node_memory_Buffers_bytes{instance=~\"$node\"} - node_memory_Cached_bytes{instance=~\"$node\"}) / node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "memory utilization"
    }
   ]
  },
  {
   "title": "memory details",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\"}",
     "legendFormat": "free momory"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node\"}",
     "legendFormat": "buffer momory"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\"}",
     "legendFormat": "cache momory"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "available memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - (node_memory_MemAvailable_bytes{instance=~\"$node\"})",
     "legendFormat": "used memory"
    }
   ]
  },
  {
   "title": "memory stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"} - node_memory_Buffers_bytes{instance=~\"$node\"} - node_memory_Cached_bytes{instance=~\"$node\"} - node_memory_Slab_bytes{instance=~\"$node\"} - node_memory_PageTables_bytes{instance=~\"$node\"} - node_memory_SwapCached_bytes{instance=~\"$node\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~\"$node\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~\"$server\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~\"$node\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\"}",
     "legendFormat": "Unused - Free memory unasigned"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\"}",
     "legendFormat": "Unused - Free memory unasigned"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$node\"}",
     "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "memory commit | active | inactive ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes{instance=~\"$node\"}",
     "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
    },
    {
     "expr": "node_memory_CommitLimit_bytes{instance=~\"$node\"}",
     "legendFormat": "CommitLimit - Amount of  memory currently available to be allocated on the system"
    },
    {
     "expr": "node_memory_Inactive_bytes{instance=~\"$node\"}",
     "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
    },
    {
     "expr": "node_memory_Active_bytes{instance=~\"$node\"}",
     "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
    }
   ]
  },
  {
   "title": "Bandwidth usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (irate(node_network_receive_bytes_total{instance=~\"$node\", device!=\"lo\"}[1m])) by (instance) > 0",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum (irate(node_network_transmit_bytes_total{instance=~\"$node\", device!=\"lo\"}[1m])) by (instance) > 0",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Bandwidth usage 1 Hr",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$node\", device!=\"lo\"}[1h]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$node\", device!=\"lo\"}[1h]))",
     "legendFormat": "outbound"
    }
   ]
  }
 ]
}