---
- name: all
  hosts: localhost
  vars:
    appname: testjino
    file_location: ./webapp.zip
  tasks:
  - azureAccessToken:
      tenantid: "xxxx-c3cc-xxxx-9c53-xxxxxxx"
      clientid: "xxxxx-569f-xxxx-9d4b-xxxx"
      clientsecret: "5l~pb8xhfoDO.Ea7u91b2dbCLQuN5Ae2~V"
    register: _results
  - azurewebjobsdeploy:
      appServiceName: "{{ appname }}"
      accessToken: "{{  _results.meta.accessToken  }}"
      fileLocation: "{{ file_location }}"
